# Define the goal
int32 id             # Specify which machine/dc robotino must go to
---
# Define the result  
bool goal_reached          # Reached destination or not
---
# Define a feedback message
# No feedback defined

