local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: false
  width: 4.0
  height: 4.0
  resolution: 0.08
